/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LangSelect: typeof import('./../components/common/LangSelect.vue')['default']
    LotteryDraw: typeof import('./../components/lottery/LotteryDraw.vue')['default']
    LotteryResult: typeof import('./../components/lottery/LotteryResult.vue')['default']
    LotteryRule: typeof import('./../components/lottery/LotteryRule.vue')['default']
    LotteryService: typeof import('./../components/lottery/LotteryService.vue')['default']
    MainButton: typeof import('./../components/base/MainButton.vue')['default']
    PressFeedback: typeof import('./../components/base/PressFeedback.vue')['default']
    PrivacyInfo: typeof import('./../components/privacy/PrivacyInfo.vue')['default']
    PrivacyPopup: typeof import('./../components/privacy/PrivacyPopup.vue')['default']
    RegionPicker: typeof import('./../components/common/RegionPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/base/SearchBar.vue')['default']
  }
}
