/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgreePrivacy: typeof import('./../components/agree-privacy/index.vue')['default']
    AreaPicker: typeof import('./../components/area-picker/index.vue')['default']
    Copyright: typeof import('./../components/copyright/index.vue')['default']
    LangSelect: typeof import('./../components/lang-select/index.vue')['default']
    PrivacyPopup: typeof import('./../components/privacy-popup/index.vue')['default']
    ResultDialog: typeof import('./../components/result-dialog/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
